create TABLE NEWS(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title TEXT,
  content TEXT,
  url VARCHAR(1000),
  created_at TIMESTAMP,
  modified_at TIMESTAMP
);

CREATE TABLE LINKS_TO_BE_PROCESSED(
  link VARCHAR(1000)
);

CREATE TABLE LINKS_ALREADY_PROCESSED(
  link VARCHAR(1000)
);